### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by benbiri** [rikkit/bath-hacked-2k15#6]
For the crime dataset they are only available on a street level. This creates an issue in associating the crimes with pubs, clubs, bars etc. where there is more than one on the same street. Do we distribute the crime level among all of them or do we apply it to the general area and display the premises included?@ryubidragonfire looking into this.

**Comment by trelltron** [comment]
One approach is to separately rate each place individually by taking all crimes within x distance, weighting them by crime type/resolution etc, dividing that rating by the root of the distance from the pub, and summing the result for each crime.

**Comment by ryubidragonfire** [comment]
Cartodb works with coordinates. coordinates from the Crime data can be used for the first layer in heatmap, as the 'heat' is directly related to the frequency of coordinates. Then we can add another layer, over the heatmap, to show location (coordinates) of pubs, car park(safe parking), house prices etc.
