### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by ryubidragonfire** [rikkit/bath-hacked-2k15#7]
Here you can find the map created

https://cyy.cartodb.com/api/v2/viz/a74eeeb4-2249-11e5-8aa0-0e853d047bba/viz.json

**Comment by issunboshi** [comment]
This can be seen on the following URL: http://rikkit.github.io/bath-hacked-2k15/

**Comment by rikkit** [comment]
hex - density of premises with alcohol licence
red dots - intensity of "violent-crime"
https://rikkit.cartodb.com/api/v2/viz/ea3d8fba-225c-11e5-8c02-0e0c41326911/viz.json

**Comment by rikkit** [comment]
hex - same
green dots - intensity of "anti-social-behaviour"
https://rikkit.cartodb.com/api/v2/viz/a647ed6c-225e-11e5-a167-0e9d821ea90d/viz.json
